#!/usr/bin/env python3
"""Generate Source/PresetConnectorCatalog.h from assets/Soundbanks/Factory Presets (category = folder, name = file stem).
The 'key' is what getFactoryPresetBinaryData() expects (same as FactoryPresetBinaryMapping.h)."""
import os, json
root = os.path.join(os.path.dirname(__file__), '..', 'assets', 'Soundbanks', 'Factory Presets')
rows = []
for cat in sorted(os.listdir(root)):
    d = os.path.join(root, cat)
    if not os.path.isdir(d): continue
    for f in sorted(os.listdir(d)):
        if f.endswith('.odin'):
            rows.append((cat, f[:-5]))
def c(s): return json.dumps(s, ensure_ascii=False)
out = ['// Generated by scripts/generate_connector_catalog.py. Do not edit.', '#pragma once', '',
       'struct ConnectorCatalogEntry { const char* category; const char* name; };',
       'static const ConnectorCatalogEntry kConnectorCatalog[] = {']
out += ['    {%s, %s},' % (c(a), c(b)) for a, b in rows]
out += ['};', 'static const int kConnectorCatalogSize = %d;' % len(rows), '']
open(os.path.join(os.path.dirname(__file__), '..', 'Source', 'PresetConnectorCatalog.h'), 'w').write('\n'.join(out))
print(len(rows), 'presets')
